import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container: {
        flex: 1,
        justifyContent: "flex-start",
        alignItems: "center",
        padding: 20,
        backgroundColor: "#f4f7fb",
    },
    title: {
        fontSize: 28,
        fontWeight: "700",
        color: "#2196F3",
        marginBottom: 24,
        textAlign: "center",
    },
    inputRow: {
        width: "100%",
        marginBottom: 16,
    },
    label: {
        fontSize: 16,
        fontWeight: "600",
        marginRight: 8,
        color: "#222",
    },
    input: {
        flex: 1,
        borderWidth: 1,
        borderColor: "#d0d5dd",
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 10,
        fontSize: 15,
        backgroundColor: "#fff",
        shadowColor: "#000",
        shadowOpacity: 0.05,
        shadowOffset: { width: 0, height: 1 },
        shadowRadius: 2,
        elevation: 1,
    },
    button: {
        backgroundColor: "#2196F3",
        paddingVertical: 12,
        paddingHorizontal: 32,
        borderRadius: 8,
        marginBottom: 20,
        marginTop: 8,
        alignSelf: "center",
        shadowColor: "#000",
        shadowOpacity: 0.1,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 4,
        elevation: 3,
    },
    buttonText: {
        color: "#fff",
        fontSize: 16,
        fontWeight: "600",
        textAlign: "center",
    },
    resultContainer: {
        backgroundColor: "#fff",
        borderRadius: 10,
        padding: 16,
        width: "100%",
        shadowColor: "#000",
        shadowOpacity: 0.05,
        shadowRadius: 4,
        elevation: 2,
        marginTop: 8,
    },
    resultText: {
        fontSize: 15,
        color: "#333",
        paddingVertical: 4,
        borderBottomWidth: 1,
        borderBottomColor: "#f0f0f0",
    },
})